"""Catalog of ML models for the LSE Terminal MACHINE LEARNING tab.

Pure data module, no third-party imports. Parameter specs mirror the ML Studio
UI (ModelRunner.tsx MODELS + MODEL_INFO), cross-checked against the argparse
interface of each training script under lse_terminal/ml/scripts/. Only
parameters the script actually accepts are listed; plumbing args the runner
supplies itself (--dataset, --timeframe, --start_date, --end_date, --features,
--job_id) are omitted.
"""

# Selectable input features (the ModelRunner '_default' feature block).
# Features are computed at training time from raw OHLCV.
FEATURES = [
    {"id": "open", "label": "Open", "category": "ohlcv", "default": True},
    {"id": "high", "label": "High", "category": "ohlcv", "default": True},
    {"id": "low", "label": "Low", "category": "ohlcv", "default": True},
    {"id": "close", "label": "Close", "category": "ohlcv", "default": True},
    {"id": "volume", "label": "Volume", "category": "volume", "default": True},
    {"id": "rsi_14", "label": "RSI (14)", "category": "momentum", "default": False},
    {"id": "rsi_7", "label": "RSI (7)", "category": "momentum", "default": False},
    {"id": "stoch_k", "label": "Stochastic %K", "category": "momentum", "default": False},
    {"id": "stoch_d", "label": "Stochastic %D", "category": "momentum", "default": False},
    {"id": "williams_r", "label": "Williams %R", "category": "momentum", "default": False},
    {"id": "cci_20", "label": "CCI (20)", "category": "momentum", "default": False},
    {"id": "roc_10", "label": "ROC (10)", "category": "momentum", "default": False},
    {"id": "roc_5", "label": "ROC (5)", "category": "momentum", "default": False},
    {"id": "mfi_14", "label": "MFI (14)", "category": "momentum", "default": False},
    {"id": "ultimate_osc", "label": "Ultimate Oscillator", "category": "momentum", "default": False},
    {"id": "awesome_osc", "label": "Awesome Oscillator", "category": "momentum", "default": False},
    {"id": "tsi", "label": "TSI", "category": "momentum", "default": False},
    {"id": "ema_9", "label": "EMA (9)", "category": "trend", "default": False},
    {"id": "ema_20", "label": "EMA (20)", "category": "trend", "default": False},
    {"id": "ema_50", "label": "EMA (50)", "category": "trend", "default": False},
    {"id": "ema_100", "label": "EMA (100)", "category": "trend", "default": False},
    {"id": "ema_200", "label": "EMA (200)", "category": "trend", "default": False},
    {"id": "sma_20", "label": "SMA (20)", "category": "trend", "default": False},
    {"id": "sma_50", "label": "SMA (50)", "category": "trend", "default": False},
    {"id": "sma_100", "label": "SMA (100)", "category": "trend", "default": False},
    {"id": "sma_200", "label": "SMA (200)", "category": "trend", "default": False},
    {"id": "macd", "label": "MACD", "category": "trend", "default": False},
    {"id": "macd_signal", "label": "MACD Signal", "category": "trend", "default": False},
    {"id": "macd_histogram", "label": "MACD Histogram", "category": "trend", "default": False},
    {"id": "adx_14", "label": "ADX (14)", "category": "trend", "default": False},
    {"id": "dema_20", "label": "DEMA (20)", "category": "trend", "default": False},
    {"id": "tema_20", "label": "TEMA (20)", "category": "trend", "default": False},
    {"id": "vwma_20", "label": "VWMA (20)", "category": "trend", "default": False},
    {"id": "hull_9", "label": "Hull MA (9)", "category": "trend", "default": False},
    {"id": "psar", "label": "Parabolic SAR", "category": "trend", "default": False},
    {"id": "plus_di", "label": "+DI (14)", "category": "trend", "default": False},
    {"id": "minus_di", "label": "-DI (14)", "category": "trend", "default": False},
    {"id": "atr_14", "label": "ATR (14)", "category": "volatility", "default": False},
    {"id": "atr_7", "label": "ATR (7)", "category": "volatility", "default": False},
    {"id": "bb_upper", "label": "BB Upper", "category": "volatility", "default": False},
    {"id": "bb_lower", "label": "BB Lower", "category": "volatility", "default": False},
    {"id": "bb_width", "label": "BB Width", "category": "volatility", "default": False},
    {"id": "bb_pctb", "label": "BB %B", "category": "volatility", "default": False},
    {"id": "keltner_upper", "label": "Keltner Upper", "category": "volatility", "default": False},
    {"id": "keltner_lower", "label": "Keltner Lower", "category": "volatility", "default": False},
    {"id": "donchian_upper", "label": "Donchian Upper (20)", "category": "volatility", "default": False},
    {"id": "donchian_lower", "label": "Donchian Lower (20)", "category": "volatility", "default": False},
    {"id": "natr_14", "label": "Normalised ATR", "category": "volatility", "default": False},
    {"id": "obv", "label": "OBV", "category": "volume_analysis", "default": False},
    {"id": "ad_line", "label": "A/D Line", "category": "volume_analysis", "default": False},
    {"id": "cmf_20", "label": "CMF (20)", "category": "volume_analysis", "default": False},
    {"id": "volume_sma_20", "label": "Volume SMA (20)", "category": "volume_analysis", "default": False},
    {"id": "force_index_13", "label": "Force Index (13)", "category": "volume_analysis", "default": False},
    {"id": "volume_roc_14", "label": "Volume ROC (14)", "category": "volume_analysis", "default": False},
    {"id": "log_return", "label": "Log Return", "category": "statistical", "default": False},
    {"id": "return_1", "label": "1-Period Return", "category": "statistical", "default": False},
    {"id": "return_5", "label": "5-Period Return", "category": "statistical", "default": False},
    {"id": "return_10", "label": "10-Period Return", "category": "statistical", "default": False},
    {"id": "return_20", "label": "20-Period Return", "category": "statistical", "default": False},
    {"id": "zscore_20", "label": "Z-Score (20)", "category": "statistical", "default": False},
    {"id": "skew_20", "label": "Skewness (20)", "category": "statistical", "default": False},
    {"id": "kurt_20", "label": "Kurtosis (20)", "category": "statistical", "default": False},
    {"id": "econ_surprise", "label": "Last Event Surprise %", "category": "economic", "default": False},
    {"id": "econ_surprise_sum", "label": "Surprise Momentum (5)", "category": "economic", "default": False},
    {"id": "econ_high_count", "label": "High Impact Events (24h)", "category": "economic", "default": False},
    {"id": "econ_medium_count", "label": "Medium Impact Events (24h)", "category": "economic", "default": False},
    {"id": "econ_low_count", "label": "Low Impact Events (24h)", "category": "economic", "default": False},
    {"id": "econ_hours_since", "label": "Hours Since Last Event", "category": "economic", "default": False},
    {"id": "econ_event_window", "label": "Active Event Window", "category": "economic", "default": False},
]

# Ordered (category_key, display_label) pairs. ModelRunner's 'risk' category
# maps to 'risk' here as well; labels follow the ML Studio sidebar.
CATEGORIES = [
    ("classification", "CLASSIFICATION"),
    ("forecasting", "FORECASTING"),
    ("deep_learning", "DEEP LEARNING"),
    ("risk", "RISK ANALYSIS"),
    ("sentiment", "SENTIMENT"),
    ("time_series", "TIME SERIES"),
]

MODELS = [
    {
        "key": "lstm_forecast",
        "name": "LSTM Price Forecast",
        "category": "forecasting",
        "description": "Deep learning recurrent neural network for sequential price prediction. LSTM gating captures long-term dependencies and non-linear temporal patterns that simpler models miss.",
        "script": "forecasting/lstm_forecaster.py",
        "features_arg": True,
        "deps": ["torch", "scikit-learn"],
        "dep_imports": ["torch", "sklearn"],
        "gpu": True,
        "params": [
            {"id": "sequence_length", "label": "Sequence Length", "type": "number", "default": 60, "min": 10, "max": 120,
             "help": "Number of past time steps the model uses to make each prediction. Longer sequences (100-200) can capture longer-term patterns but increase training time and memory usage. Shorter sequences (20-50) train faster but may miss important context. For minute data, 60 (1 hour) is a good starting point."},
            {"id": "forecast_horizon", "label": "Forecast Horizon", "type": "number", "default": 10, "min": 1, "max": 60,
             "help": "How many steps ahead to predict. Single-step (1) is most accurate. Multi-step (5-20) enables trajectory forecasting but compounds errors. Use teacher forcing during training for multi-step predictions."},
            {"id": "test_size", "label": "Test Split %", "type": "number", "default": 20, "min": 1, "max": 99, "step": 1,
             "help": "Percentage of data reserved for final evaluation. Unlike random splits, time series uses the most recent data for testing to simulate real-world deployment. 20% is standard."},
            {"id": "lstm_units", "label": "LSTM Units", "type": "number", "default": 128, "min": 32, "max": 256, "step": 32,
             "help": "Number of memory cells in each LSTM layer. More units (256-512) increase model capacity but risk overfitting. Fewer units (32-64) are more generalizable. Start with 128 and adjust based on validation performance."},
            {"id": "num_layers", "label": "LSTM Layers", "type": "number", "default": 2, "min": 1, "max": 3,
             "help": "Number of stacked LSTM layers. Deeper networks (3-4 layers) can learn hierarchical patterns but are harder to train. Most financial applications work well with 2 layers. Use dropout between layers to prevent overfitting."},
            {"id": "dense_units", "label": "Dense Units", "type": "number", "default": 64, "min": 16, "max": 128, "step": 16,
             "help": "Size of the fully connected layer after LSTM processing. This layer maps the LSTM output to the final prediction. Typically set to half the LSTM units."},
            {"id": "epochs", "label": "Training Epochs", "type": "number", "default": 100, "min": 10, "max": 200, "step": 10,
             "help": "Maximum training iterations over the entire dataset. More epochs allow the model to converge but risk overfitting. With early stopping, set this high (100-500) and let validation loss determine when to stop."},
            {"id": "batch_size", "label": "Batch Size", "type": "number", "default": 256, "min": 32, "max": 1024, "step": 32,
             "help": "Number of sequences processed before updating weights. Smaller batches (16-32) provide noisier but more frequent updates. Larger batches (64-128) are more stable but may get stuck in local minima. Affects memory usage significantly."},
            {"id": "learning_rate", "label": "Learning Rate", "type": "number", "default": 0.001, "min": 0.0001, "max": 0.01, "step": 0.0001,
             "help": "Controls step size during gradient descent. Too high (above 0.01) causes unstable training and NaN losses. Too low (below 0.0001) trains very slowly. Start with 0.001 (Adam default)."},
            {"id": "dropout", "label": "Dropout Rate", "type": "number", "default": 0.2, "min": 0, "max": 0.5, "step": 0.05,
             "help": "Fraction of neurons randomly disabled during training to prevent overfitting. Applied between LSTM layers and before the output layer. 0.2-0.3 is typical. Increase if you observe significant train/test performance gaps."},
            {"id": "early_stopping", "label": "Early Stopping Patience", "type": "number", "default": 10, "min": 5, "max": 50, "step": 5,
             "help": "Stops training when validation loss stops improving for this many epochs. Prevents overfitting by selecting the model from the best epoch. Set to 10-20 for most applications. Lower values may stop too early."},
        ],
    },
    {
        "key": "arima_forecast",
        "name": "ARIMA/SARIMA Forecast",
        "category": "forecasting",
        "description": "Statistical autoregressive integrated moving average model for time series. Provides interpretable coefficients and confidence intervals, with optional seasonal (SARIMA) components.",
        "script": "forecasting/arima_forecaster.py",
        "features_arg": True,
        "deps": ["statsmodels", "scikit-learn"],
        "dep_imports": ["statsmodels", "sklearn"],
        "gpu": False,
        "params": [
            {"id": "forecast_horizon", "label": "Forecast Horizon", "type": "number", "default": 30, "min": 1, "max": 60,
             "help": "Number of periods to forecast ahead. ARIMA confidence intervals widen significantly for longer horizons. Most reliable for short-term (1-30 periods) forecasting."},
            {"id": "test_size", "label": "Test Split %", "type": "number", "default": 20, "min": 1, "max": 99, "step": 1,
             "help": "Percentage held out for evaluation. Uses walk-forward validation, training on past data and testing on future data in sequence."},
            {"id": "p", "label": "AR Order (p)", "type": "number", "default": 2, "min": 0, "max": 10,
             "help": "AR (AutoRegressive) order, the number of lagged observations. Higher p captures longer memory in the series. Determined by PACF analysis. Typical values: 1-5 for financial data."},
            {"id": "d", "label": "Differencing (d)", "type": "number", "default": 1, "min": 0, "max": 3,
             "help": "Differencing order, how many times to difference the series for stationarity. d=1 for trending series, d=2 for accelerating trends. Most financial series need d=1."},
            {"id": "q", "label": "MA Order (q)", "type": "number", "default": 2, "min": 0, "max": 10,
             "help": "MA (Moving Average) order, the number of lagged forecast errors. Higher q smooths out noise. Determined by ACF analysis. Start with q=1-2."},
            {"id": "seasonal_p", "label": "Seasonal AR (P)", "type": "number", "default": 1, "min": 0, "max": 5,
             "help": "Seasonal AR order. Captures autoregressive patterns at seasonal lags. For hourly data with daily seasonality, this looks at same-hour-yesterday patterns."},
            {"id": "seasonal_d", "label": "Seasonal Diff (D)", "type": "number", "default": 1, "min": 0, "max": 2,
             "help": "Seasonal differencing. Usually 0 or 1. Use 1 if the series has strong seasonal trends that simple differencing does not remove."},
            {"id": "seasonal_q", "label": "Seasonal MA (Q)", "type": "number", "default": 1, "min": 0, "max": 5,
             "help": "Seasonal MA order. Models seasonal forecast errors. Keep low (0-2) to avoid overfitting."},
            {"id": "seasonal_period", "label": "Seasonal Period", "type": "number", "default": 60, "min": 1, "max": 720,
             "help": "Length of the seasonal cycle in periods. For 1-minute crypto data: 60 (hourly), 1440 (daily), 10080 (weekly). Correct period is crucial for seasonal models."},
            {"id": "trend", "label": "Trend Component", "type": "select", "default": "c",
             "options": [{"value": "n", "label": "No Trend"}, {"value": "c", "label": "Constant Only"},
                         {"value": "t", "label": "Linear Trend"}, {"value": "ct", "label": "Constant + Trend"}],
             "help": "Trend component to include. c (constant/intercept) is most common. t adds a linear time trend. ct combines both. n for no trend in mean-reverting series."},
            {"id": "auto_order", "label": "Auto-Select Orders", "type": "select", "default": "false",
             "options": [{"value": "false", "label": "Use Manual Orders"}, {"value": "true", "label": "Auto-ARIMA (AIC)"}],
             "help": "Automatically select p, d, q using AIC (Akaike Information Criterion). Searches the model space to find optimal orders. Slower but often finds better models than manual selection."},
        ],
    },
    {
        "key": "transformer_forecast",
        "name": "Transformer Price Forecast",
        "category": "forecasting",
        "description": "Attention-based neural network for sequential prediction. Self-attention attends to all positions at once, capturing long-range dependencies faster than recurrent models.",
        "script": "forecasting/transformer_forecaster.py",
        "features_arg": True,
        "deps": ["torch"],
        "dep_imports": ["torch"],
        "gpu": True,
        "params": [
            {"id": "sequence_length", "label": "Context Window", "type": "number", "default": 64, "min": 32, "max": 128, "step": 32,
             "help": "Number of past time steps the model attends to. Longer windows capture broader context but require more memory and compute. The attention mechanism lets Transformers handle longer sequences more effectively than LSTMs."},
            {"id": "forecast_horizon", "label": "Forecast Steps", "type": "number", "default": 12, "min": 1, "max": 60,
             "help": "Number of steps to predict ahead. Multi-step forecasting is handled via autoregressive decoding. Shorter horizons (1-12 steps) are more reliable."},
            {"id": "d_model", "label": "Model Dimension", "type": "number", "default": 64, "min": 32, "max": 64, "step": 32,
             "help": "Dimensionality of the internal representations. Larger values increase model capacity but require more data to train effectively. 64 is a reasonable starting point for financial data."},
            {"id": "n_heads", "label": "Attention Heads", "type": "number", "default": 4, "min": 1, "max": 8,
             "help": "Number of parallel attention heads. Each head learns to focus on different temporal patterns. Must divide evenly into the model dimension. 4-8 heads is typical."},
            {"id": "epochs", "label": "Training Epochs", "type": "number", "default": 50, "min": 10, "max": 100, "step": 10,
             "help": "Maximum training iterations. With early stopping, set this conservatively high and let the validation loss determine when to stop."},
        ],
    },
    {
        "key": "prophet_forecast",
        "name": "Prophet Forecast",
        "category": "forecasting",
        "description": "Decomposable time series model that separates trend and seasonality components. Robust to outliers and missing data, well suited to series with strong cyclical patterns.",
        "script": "forecasting/prophet_forecaster.py",
        "features_arg": True,
        # The script is a pure NumPy Prophet-style decomposition; the prophet
        # pip package is NOT required.
        "deps": [],
        "dep_imports": [],
        "gpu": False,
        "params": [
            {"id": "forecast_horizon", "label": "Forecast Periods", "type": "number", "default": 24, "min": 1, "max": 100,
             "help": "Number of future periods to predict. Uncertainty widens for longer horizons. Short-term forecasts (24-48 periods) are most reliable."},
            {"id": "growth", "label": "Growth Type", "type": "select", "default": "linear",
             "options": [{"value": "linear", "label": "Linear"}, {"value": "logistic", "label": "Logistic (Capped)"},
                         {"value": "flat", "label": "Flat (No Trend)"}],
             "help": "Trend component type. Linear growth assumes a constant rate of change. Logistic growth models saturating trends with a carrying capacity. Flat removes the trend component entirely for mean-reverting series."},
            {"id": "seasonality_mode", "label": "Seasonality Mode", "type": "select", "default": "multiplicative",
             "options": [{"value": "additive", "label": "Additive"}, {"value": "multiplicative", "label": "Multiplicative"}],
             "help": "How seasonal effects combine with the trend. Additive assumes seasonal fluctuations are constant regardless of the trend level. Multiplicative assumes they scale proportionally, more appropriate for financial data where volatility increases with price."},
            # UI id is changepoint_prior_scale; the script argparse accepts --changepoint_scale.
            {"id": "changepoint_scale", "label": "Changepoint Flexibility", "type": "number", "default": 0.05, "min": 0.001, "max": 0.5, "step": 0.01,
             "help": "Controls how flexible the trend is at adapting to changes. Higher values (0.1-0.5) allow the trend to shift more readily, which may overfit. Lower values (0.001-0.05) produce smoother, more conservative trends."},
        ],
    },
    {
        "key": "xgboost_price",
        "name": "XGBoost Price Predictor",
        "category": "classification",
        "description": "Gradient boosting classifier over candle features and technical indicators. Builds trees sequentially, each correcting the errors of the previous ones.",
        "script": "xgboost_classifier.py",
        "features_arg": True,
        "deps": ["xgboost", "scikit-learn", "joblib"],
        "dep_imports": ["xgboost", "sklearn", "joblib"],
        "gpu": True,
        "params": [
            {"id": "target_horizon", "label": "Prediction Horizon", "type": "select", "default": "5",
             "options": [{"value": "1", "label": "1 Candle"}, {"value": "5", "label": "5 Candles"},
                         {"value": "10", "label": "10 Candles"}, {"value": "15", "label": "15 Candles"}],
             "help": "How many candles ahead the model should predict. Shorter horizons (1-5 candles) are generally easier to predict with higher accuracy but offer less time to act. Longer horizons (10-15 candles) are harder to predict but provide more actionable trading signals."},
            {"id": "test_size", "label": "Test Split %", "type": "number", "default": 20, "min": 1, "max": 99, "step": 1,
             "help": "The percentage of data held out for testing model performance. A 20% split is standard practice. Higher values give more reliable accuracy estimates but leave less data for training."},
            {"id": "n_estimators", "label": "Number of Trees", "type": "number", "default": 100, "min": 50, "max": 500, "step": 50,
             "help": "The number of trees (boosting rounds) to build. More trees can capture complex patterns and improve accuracy, but also increase training time and risk overfitting. With early stopping enabled you can set this high and let the algorithm stop when performance plateaus."},
            {"id": "max_depth", "label": "Tree Depth", "type": "number", "default": 6, "min": 2, "max": 15,
             "help": "Controls how deep each decision tree can grow. Deeper trees (8-15) can model complex feature interactions but are prone to overfitting. The sweet spot for financial data is typically 4-6. Reduce if you see large gaps between training and test accuracy."},
            {"id": "learning_rate", "label": "Learning Rate", "type": "number", "default": 0.1, "min": 0.01, "max": 0.5, "step": 0.01,
             "help": "Also called eta. Controls how much each tree contributes to the final prediction. Lower values (0.01-0.05) make training more conservative and require more trees, but often achieve better generalization. Higher values (0.1-0.3) train faster but may overshoot optimal solutions."},
            {"id": "min_child_weight", "label": "Min Child Weight", "type": "number", "default": 1, "min": 1, "max": 10,
             "help": "The minimum sum of instance weight (hessian) needed in a child node. Higher values (3-10) make the algorithm more conservative by preventing leaves that are too specific to small data subsets. Increase this if you observe overfitting."},
            {"id": "subsample", "label": "Subsample Ratio", "type": "number", "default": 0.8, "min": 0.5, "max": 1.0, "step": 0.05,
             "help": "Fraction of training samples used to build each tree. Values below 1.0 introduce randomness that helps prevent overfitting, similar to bagging in Random Forest. Standard range: 0.7-0.9."},
            {"id": "colsample_bytree", "label": "Column Sample", "type": "number", "default": 0.8, "min": 0.5, "max": 1.0, "step": 0.05,
             "help": "Fraction of features (columns) randomly selected for each tree. Adds regularisation through randomness. Values of 0.7-0.9 are common. Lower values can help when you have many correlated features, common with technical indicators."},
            {"id": "reg_alpha", "label": "L1 Regularisation", "type": "number", "default": 0, "min": 0, "max": 10, "step": 0.1,
             "help": "L1 regularisation on leaf weights. Encourages sparse models by pushing small weights toward zero, effectively performing feature selection. Start with 0 and increase (0.1-1.0) if you want the model to focus on fewer, more important features."},
            {"id": "reg_lambda", "label": "L2 Regularisation", "type": "number", "default": 1, "min": 0, "max": 10, "step": 0.1,
             "help": "L2 regularisation on leaf weights. Shrinks all weights proportionally rather than eliminating them, preventing any single feature from dominating. The default of 1 provides moderate regularisation. Increase (2-10) for more conservative models."},
            {"id": "early_stopping_rounds", "label": "Early Stopping", "type": "number", "default": 10, "min": 5, "max": 50, "step": 5,
             "help": "Training stops if validation performance does not improve for this many consecutive rounds. Prevents overfitting by stopping at the optimal number of trees rather than a fixed number. Set to 10-20 for quick experiments, 30-50 for final models."},
        ],
    },
    {
        "key": "random_forest",
        "name": "Random Forest Classifier",
        "category": "classification",
        "description": "Ensemble of decision trees with bagging for robust classification. Trees are built independently and vote on the prediction, giving natural overfitting resistance and a free out-of-bag validation estimate.",
        "script": "classification/random_forest_classifier.py",
        "features_arg": True,
        "deps": ["scikit-learn"],
        "dep_imports": ["sklearn"],
        "gpu": False,
        "params": [
            {"id": "target_horizon", "label": "Prediction Horizon", "type": "number", "default": 5, "min": 1, "max": 60,
             "help": "Future candles to predict for creating the target variable. The model learns to classify whether price will be higher or lower after this many periods."},
            {"id": "test_size", "label": "Test Split %", "type": "number", "default": 20, "min": 1, "max": 99, "step": 1,
             "help": "Holdout percentage for final evaluation. With OOB score enabled, you also get a reliable estimate from the training set itself."},
            {"id": "n_estimators", "label": "Number of Trees", "type": "number", "default": 200, "min": 50, "max": 500, "step": 50,
             "help": "Number of trees in the forest. More trees generally improve performance with diminishing returns after 200-500. Training time scales linearly. Monitor OOB error to find the optimal number."},
            {"id": "max_depth", "label": "Max Depth", "type": "number", "default": 10, "min": 3, "max": 20,
             "help": "Maximum depth of each tree. Deep trees (20-30) can capture complex interactions but may memorize noise. Shallow trees (5-10) are more robust but may underfit."},
            {"id": "min_samples_split", "label": "Min Samples Split", "type": "number", "default": 5, "min": 2, "max": 50,
             "help": "Minimum samples required to split an internal node. Higher values (10-50) create more general trees. Helps prevent splits on small, potentially noisy subsets."},
            {"id": "min_samples_leaf", "label": "Min Samples Leaf", "type": "number", "default": 2, "min": 1, "max": 20,
             "help": "Minimum samples required in each leaf node. Ensures every prediction is based on sufficient data. Higher values smooth the model and reduce variance. Critical for noisy financial data."},
            {"id": "max_features", "label": "Max Features", "type": "select", "default": "sqrt",
             "options": [{"value": "sqrt", "label": "Square Root"}, {"value": "log2", "label": "Log2"},
                         {"value": "auto", "label": "All Features"}, {"value": "0.5", "label": "50% of Features"}],
             "help": "Number of features considered for each split. sqrt (most common for classification) decorrelates trees. Lower values increase randomness and reduce overfitting. log2 is even more conservative."},
            {"id": "criterion", "label": "Split Criterion", "type": "select", "default": "gini",
             "options": [{"value": "gini", "label": "Gini Impurity"}, {"value": "entropy", "label": "Information Gain"},
                         {"value": "log_loss", "label": "Log Loss"}],
             "help": "Function to measure split quality. Gini impurity is faster and often sufficient. Entropy (information gain) can find more balanced splits. Log loss is designed for probability estimation."},
            {"id": "bootstrap", "label": "Bootstrap Samples", "type": "select", "default": "true",
             "options": [{"value": "true", "label": "Yes (Bagging)"}, {"value": "false", "label": "No (Pasting)"}],
             "help": "Whether to sample with replacement. Bagging (Yes) creates diverse trees by training on different subsets. Pasting (No) uses all data but with random feature selection. Bagging is standard and enables OOB estimation."},
            {"id": "oob_score", "label": "Out-of-Bag Score", "type": "select", "default": "true",
             "options": [{"value": "true", "label": "Calculate OOB"}, {"value": "false", "label": "Skip OOB"}],
             "help": "Calculate out-of-bag error estimate. Each tree is evaluated on samples not used in its training (about 37% of data due to bootstrap). Provides an honest accuracy estimate without a separate validation set."},
            {"id": "class_weight", "label": "Class Weights", "type": "select", "default": "balanced",
             "options": [{"value": "balanced", "label": "Balanced"}, {"value": "none", "label": "None"}],
             "help": "Adjust weights for imbalanced classes. Balanced weights classes inversely proportional to their frequency. Critical for financial data where profitable signals may be rare."},
        ],
    },
    {
        "key": "lightgbm",
        "name": "LightGBM Classifier",
        "category": "classification",
        "description": "Microsoft's fast gradient boosting with leaf-wise tree growth. Produces deeper, more specialised trees that often reach higher accuracy in fewer iterations than level-wise boosting.",
        "script": "classification/lightgbm_classifier.py",
        "features_arg": True,
        "deps": ["lightgbm", "scikit-learn"],
        "dep_imports": ["lightgbm", "sklearn"],
        "gpu": True,
        "params": [
            {"id": "target_horizon", "label": "Prediction Horizon", "type": "number", "default": 5, "min": 1, "max": 60,
             "help": "Number of future candles used to determine the classification label (up/down). Shorter horizons are noisier but more responsive; longer horizons provide clearer trends."},
            {"id": "test_size", "label": "Test Split %", "type": "number", "default": 20, "min": 1, "max": 99, "step": 1,
             "help": "Percentage of data held out for evaluation. Uses chronological splitting to prevent look-ahead bias."},
            {"id": "n_estimators", "label": "Number of Trees", "type": "number", "default": 200, "min": 50, "max": 500, "step": 50,
             "help": "Number of boosting rounds (trees). With early stopping, set this high and let the algorithm determine the optimal number."},
            {"id": "max_depth", "label": "Max Depth", "type": "number", "default": -1, "min": -1, "max": 20,
             "help": "Maximum tree depth. Set to -1 for no limit. Explicitly limiting depth (6-12) can prevent excessively complex trees."},
            {"id": "learning_rate", "label": "Learning Rate", "type": "number", "default": 0.1, "min": 0.01, "max": 0.5, "step": 0.01,
             "help": "Shrinkage rate applied to each tree. Lower values (0.01-0.05) require more trees but often generalise better. Higher values (0.1-0.3) train faster at the cost of potential overfitting."},
        ],
    },
    {
        "key": "catboost",
        "name": "CatBoost Direction Predictor",
        "category": "classification",
        "description": "Yandex gradient boosting with ordered boosting and native categorical feature handling. Achieves strong performance with minimal hyperparameter tuning.",
        "script": "classification/catboost_predictor.py",
        "features_arg": True,
        "deps": ["catboost", "scikit-learn"],
        "dep_imports": ["catboost", "sklearn"],
        "gpu": True,
        "params": [
            {"id": "target_horizon", "label": "Prediction Horizon", "type": "number", "default": 5, "min": 1, "max": 60,
             "help": "Number of future candles used to create the target label. Determines whether the model predicts short-term movements or longer-term trend direction."},
            {"id": "test_size", "label": "Test Split %", "type": "number", "default": 20, "min": 1, "max": 99, "step": 1,
             "help": "Percentage of recent data reserved for evaluation. Chronological splitting ensures no future information leaks into training."},
            {"id": "iterations", "label": "Iterations", "type": "number", "default": 500, "min": 100, "max": 1000, "step": 100,
             "help": "Maximum number of boosting rounds. Higher values allow more refinement but increase training time."},
            {"id": "depth", "label": "Tree Depth", "type": "number", "default": 6, "min": 2, "max": 16,
             "help": "Depth of each decision tree. CatBoost builds balanced (symmetric) trees, so depth directly controls complexity. 6-8 is typical; deeper trees (10-16) may overfit on noisy financial data."},
            {"id": "learning_rate", "label": "Learning Rate", "type": "number", "default": 0.03, "min": 0.001, "max": 0.3, "step": 0.01,
             "help": "Step size for each boosting iteration. Lower values (0.01-0.05) with more iterations often yield better results."},
        ],
    },
    {
        "key": "mlp",
        "name": "Neural Network (MLP)",
        "category": "classification",
        "description": "Multi-layer perceptron with configurable hidden layers. Learns non-linear decision boundaries over the feature vector at each time step; a fast baseline classifier.",
        "script": "classification/mlp_classifier.py",
        "features_arg": True,
        # sklearn's MLPClassifier is a full implementation, so torch is not
        # required here; when torch IS installed the script trains on the
        # GPU (CUDA, or MPS on Apple Silicon).
        "deps": ["scikit-learn"],
        "dep_imports": ["sklearn"],
        "gpu": True,
        "params": [
            {"id": "target_horizon", "label": "Prediction Horizon", "type": "number", "default": 5, "min": 1, "max": 60,
             "help": "Number of future candles used to determine the classification target. The model learns whether the price will be higher or lower after this many periods."},
            {"id": "test_size", "label": "Test Split %", "type": "number", "default": 20, "min": 1, "max": 99, "step": 1,
             "help": "Percentage of data reserved for out-of-sample evaluation. Chronological splitting is used to prevent look-ahead bias."},
            # The UI exposes hidden_layer_1/2/3 separately; the script takes one
            # comma separated --hidden_layers string.
            {"id": "hidden_layers", "label": "Hidden Layers", "type": "text", "default": "128,64,32",
             "help": "Comma separated neuron counts for each hidden layer, largest first (for example 128,64,32). Fewer or smaller layers train faster; deeper networks can model more complex relationships but need more data and regularisation."},
            # UI id max_iter maps to the script's --epochs.
            {"id": "epochs", "label": "Training Epochs", "type": "number", "default": 300, "min": 100, "max": 500, "step": 50,
             "help": "Maximum number of training iterations (epochs). The solver will stop early if the loss converges. Set this high enough (300-1000) to ensure convergence."},
            # UI id learning_rate_init maps to the script's --learning_rate.
            {"id": "learning_rate", "label": "Learning Rate", "type": "number", "default": 0.001, "min": 0.0001, "max": 0.1, "step": 0.0001,
             "help": "Initial learning rate for the optimiser. Controls the step size during weight updates. 0.001 is the standard starting point. Reduce if training is unstable."},
        ],
    },
    {
        "key": "garch_volatility",
        "name": "GARCH Volatility Model",
        "category": "risk",
        "description": "Generalized autoregressive conditional heteroskedasticity for volatility forecasting. Models volatility clustering, essential for risk management and position sizing.",
        "script": "risk_analysis/garch_volatility.py",
        "features_arg": True,
        # arch is the primary engine; the script has a numpy GARCH(1,1) fallback.
        "deps": ["arch", "scikit-learn"],
        "dep_imports": ["arch", "sklearn"],
        "gpu": False,
        "params": [
            {"id": "forecast_horizon", "label": "Forecast Horizon", "type": "number", "default": 30, "min": 1, "max": 100,
             "help": "How many periods ahead to forecast volatility. Short-term forecasts (1-5 periods) are most reliable. Longer horizons converge to long-run average volatility."},
            {"id": "test_size", "label": "Test Split %", "type": "number", "default": 20, "min": 1, "max": 99, "step": 1,
             "help": "Data reserved for out-of-sample evaluation of volatility forecasts. Assessed using realized volatility as the benchmark."},
            {"id": "p", "label": "GARCH Order (p)", "type": "number", "default": 1, "min": 1, "max": 5,
             "help": "GARCH order, the number of lagged conditional variance terms. p=1 is sufficient for most applications. Higher orders rarely improve forecasts and can cause estimation issues."},
            {"id": "q", "label": "ARCH Order (q)", "type": "number", "default": 1, "min": 1, "max": 5,
             "help": "ARCH order, the number of lagged squared return terms. q=1 captures the immediate volatility shock. Higher values (q=2-3) may help for very noisy series."},
            {"id": "o", "label": "Asymmetry Order (o)", "type": "number", "default": 0, "min": 0, "max": 3,
             "help": "Asymmetry order for leverage effects. Negative returns increase volatility more than positive returns of the same magnitude. o=1 captures this leverage effect."},
            {"id": "model_type", "label": "Volatility Model", "type": "select", "default": "GARCH",
             "options": [{"value": "GARCH", "label": "Standard GARCH"}, {"value": "EGARCH", "label": "Exponential GARCH"},
                         {"value": "TGARCH", "label": "Threshold GARCH"}, {"value": "FIGARCH", "label": "Fractionally Integrated"}],
             "help": "Volatility model variant: Standard GARCH is symmetric. EGARCH captures asymmetry with log variance. TGARCH (GJR) adds a threshold for negative returns. FIGARCH models long memory in volatility."},
            {"id": "distribution", "label": "Error Distribution", "type": "select", "default": "t",
             "options": [{"value": "normal", "label": "Normal (Gaussian)"}, {"value": "t", "label": "Student's t"},
                         {"value": "skewt", "label": "Skewed t"}, {"value": "ged", "label": "Generalized Error"}],
             "help": "Distribution assumption for standardized residuals. Financial returns are heavy-tailed, making Student's t or GED better than Normal. Skewed t adds asymmetry for even better fit."},
            {"id": "mean_model", "label": "Mean Model", "type": "select", "default": "Constant",
             "options": [{"value": "Zero", "label": "Zero Mean"}, {"value": "Constant", "label": "Constant Mean"},
                         {"value": "AR", "label": "AR(1) Mean"}, {"value": "ARX", "label": "ARX with Exogenous"}],
             "help": "Model for the conditional mean (expected return). Constant is most common. AR(1) can capture momentum. Zero mean is appropriate for very short intervals."},
            {"id": "rescale", "label": "Rescale Data", "type": "select", "default": "true",
             "options": [{"value": "true", "label": "Yes (Recommended)"}, {"value": "false", "label": "No"}],
             "help": "Multiply returns by 100 before estimation. Improves numerical stability for small return values. Recommended for crypto where raw returns are often below 0.001."},
        ],
    },
    {
        "key": "monte_carlo",
        "name": "Monte Carlo Simulation",
        "category": "risk",
        "description": "Stochastic price path simulation using geometric Brownian motion and related processes. Quantifies uncertainty and tail risk for VaR, CVaR, and scenario analysis.",
        "script": "risk_analysis/monte_carlo_simulation.py",
        "features_arg": True,
        "deps": ["scipy"],
        "dep_imports": ["scipy"],
        "gpu": False,
        "params": [
            {"id": "num_simulations", "label": "Simulation Paths", "type": "number", "default": 10000, "min": 1000, "max": 50000, "step": 1000,
             "help": "Number of random paths to generate. More paths give more stable risk estimates. 10,000 is common for VaR. Computation scales linearly."},
            {"id": "time_horizon", "label": "Time Horizon (periods)", "type": "number", "default": 252, "min": 1, "max": 1000,
             "help": "How many periods to simulate forward. Risk metrics compound over longer horizons. Match to your actual holding period."},
            {"id": "confidence_level", "label": "Confidence Level %", "type": "number", "default": 95, "min": 90, "max": 99, "step": 1,
             "help": "Percentile for VaR calculation. 95% means the loss will exceed VaR only 5% of the time. 99% is more conservative. Higher confidence means larger reported risk."},
            {"id": "price_model", "label": "Price Model", "type": "select", "default": "gbm",
             "options": [{"value": "gbm", "label": "Geometric Brownian Motion"}, {"value": "jump_diffusion", "label": "Merton Jump Diffusion"},
                         {"value": "heston", "label": "Heston Stochastic Vol"}, {"value": "variance_gamma", "label": "Variance Gamma"}],
             "help": "Stochastic process for price evolution. GBM assumes constant volatility. Jump-diffusion adds sudden price jumps. Heston models stochastic volatility. Variance Gamma captures skewness and fat tails."},
            {"id": "vol_method", "label": "Volatility Method", "type": "select", "default": "historical",
             "options": [{"value": "historical", "label": "Historical Volatility"}, {"value": "ewma", "label": "EWMA (lambda=0.94)"},
                         {"value": "garch", "label": "GARCH(1,1) Forecast"}, {"value": "realized", "label": "Realized Volatility"}],
             "help": "How to estimate future volatility. Historical uses simple standard deviation. EWMA weights recent data more heavily (lambda=0.94 is the RiskMetrics standard). GARCH forecasts conditional volatility. Realized volatility uses high-frequency data."},
            {"id": "lookback_window", "label": "Volatility Lookback", "type": "number", "default": 252, "min": 21, "max": 500,
             "help": "Historical periods for volatility estimation. Shorter windows (21-63) adapt quickly to changing volatility. Longer windows (252) provide more stable estimates but may miss regime changes."},
            {"id": "var_method", "label": "VaR Method", "type": "select", "default": "historical",
             "options": [{"value": "historical", "label": "Historical Simulation"}, {"value": "parametric", "label": "Parametric (Delta-Normal)"},
                         {"value": "cornish_fisher", "label": "Cornish-Fisher Expansion"}],
             "help": "VaR calculation methodology. Historical simulation uses actual return percentiles. Parametric assumes a normal distribution. Cornish-Fisher adjusts for skewness and kurtosis."},
            {"id": "calculate_cvar", "label": "Calculate CVaR", "type": "select", "default": "true",
             "options": [{"value": "true", "label": "Yes (Expected Shortfall)"}, {"value": "false", "label": "VaR Only"}],
             "help": "Conditional VaR (Expected Shortfall), the average loss in the worst X% of scenarios. More informative than VaR for tail risk. Required by Basel III for market risk capital."},
            {"id": "random_seed", "label": "Random Seed", "type": "number", "default": 42, "min": 1, "max": 99999,
             "help": "Seed for reproducible results. The same seed generates identical random paths, useful for comparing models. Set to different values for true randomization."},
        ],
    },
    {
        "key": "var",
        "name": "Value at Risk (VaR)",
        "category": "risk",
        "description": "Historical, parametric, Cornish-Fisher, and EWMA Value at Risk estimation. Quantifies the maximum expected loss over a holding period at a chosen confidence level.",
        "script": "risk_analysis/var_calculator.py",
        "features_arg": True,
        "deps": ["scipy"],
        "dep_imports": ["scipy"],
        "gpu": False,
        "params": [
            # UI id confidence_level; the script argparse accepts --confidence.
            {"id": "confidence", "label": "Confidence %", "type": "number", "default": 95, "min": 90, "max": 99.9, "step": 0.5,
             "help": "The probability level for the VaR estimate. 95% is standard for internal risk management. 99% is used for regulatory capital requirements (Basel III). Higher confidence produces larger risk estimates."},
            # UI id time_horizon; the script argparse accepts --holding_period.
            {"id": "holding_period", "label": "Time Horizon (days)", "type": "number", "default": 1, "min": 1, "max": 30,
             "help": "The holding period in days over which losses are measured. 1-day VaR is most common. For longer horizons, VaR scales approximately by the square root of time."},
            {"id": "method", "label": "VaR Method", "type": "select", "default": "historical",
             "options": [{"value": "historical", "label": "Historical Simulation"}, {"value": "parametric", "label": "Parametric (Normal)"},
                         {"value": "cornish_fisher", "label": "Cornish-Fisher"}, {"value": "ewma", "label": "EWMA (lambda=0.94)"}],
             "help": "Calculation methodology. Historical simulation uses actual return percentiles, model-free but data hungry. Parametric assumes a normal distribution, fast but underestimates tail risk. Cornish-Fisher adjusts for skewness and kurtosis. EWMA weights recent observations more heavily."},
            {"id": "portfolio_value", "label": "Portfolio Value ($)", "type": "number", "default": 100000, "min": 1000, "max": 100000000, "step": 1000,
             "help": "Total portfolio value in the base currency. Used to convert percentage-based VaR into an absolute monetary figure. Set to your actual position size for meaningful risk estimates."},
        ],
    },
    {
        "key": "copula",
        "name": "Copula Dependency Model",
        "category": "risk",
        "description": "Models the joint distribution and tail dependencies between assets. Separates marginal distributions from the dependence structure to reveal co-movement during market stress.",
        "script": "risk_analysis/copula_dependency.py",
        "features_arg": True,
        "deps": ["scipy"],
        "dep_imports": ["scipy"],
        "gpu": False,
        "params": [
            {"id": "copula_type", "label": "Copula Type", "type": "select", "default": "gaussian",
             "options": [{"value": "gaussian", "label": "Gaussian"}, {"value": "t", "label": "Student-t"},
                         {"value": "clayton", "label": "Clayton (Lower Tail)"}, {"value": "gumbel", "label": "Gumbel (Upper Tail)"},
                         {"value": "frank", "label": "Frank (Symmetric)"}],
             "help": "The copula family to fit. Gaussian assumes symmetric, moderate dependence. Student-t adds tail dependence (both assets move together in extremes). Clayton emphasises lower-tail dependence (crashes). Gumbel emphasises upper-tail dependence (rallies). Frank provides symmetric dependence without tail effects."},
            # Script-only parameter; the UI instead offers a secondary_asset picker
            # which this script does not accept.
            {"id": "num_assets", "label": "Number of Assets", "type": "number", "default": 3, "min": 2, "max": 10,
             "help": "How many assets to include in the dependency structure. The copula is fitted over the joint returns of this many series."},
        ],
    },
    {
        "key": "hmm",
        "name": "Regime Switching (HMM)",
        "category": "risk",
        "description": "Detects latent market regimes such as trending, mean-reverting, or high-volatility states. Useful for adapting strategy selection and exposure as conditions change.",
        "script": "risk_analysis/regime_switching_hmm.py",
        "features_arg": True,
        # The script implements KMeans-based regime detection via scikit-learn;
        # hmmlearn is NOT required.
        "deps": ["scikit-learn"],
        "dep_imports": ["sklearn"],
        "gpu": False,
        "params": [
            {"id": "n_regimes", "label": "Number of Regimes", "type": "number", "default": 3, "min": 2, "max": 5,
             "help": "Number of distinct market states to identify. Two regimes capture bull/bear or high/low volatility. Three regimes add a transitional state. More than four rarely improves interpretability."},
            # UI id n_iter; the script argparse accepts --n_iterations.
            {"id": "n_iterations", "label": "EM Iterations", "type": "number", "default": 100, "min": 10, "max": 500,
             "help": "Maximum fitting iterations. More iterations improve convergence but increase computation. 100 is typically sufficient."},
        ],
    },
    {
        "key": "pca_analysis",
        "name": "PCA Factor Analysis (3D)",
        "category": "risk",
        "description": "Principal component analysis of the selected feature set. Finds the few independent factors that drive most of the variation, then projects every bar onto the three dominant components in an interactive 3D view with explained variance and factor loadings.",
        "script": "risk_analysis/pca_analysis.py",
        "features_arg": True,
        # Pure NumPy eigendecomposition; scikit-learn is NOT required.
        "deps": [],
        "dep_imports": [],
        "gpu": False,
        "params": [
            {"id": "basis", "label": "Basis", "type": "select", "default": "correlation",
             "options": [{"value": "correlation", "label": "Correlation (standardized)"},
                         {"value": "covariance", "label": "Covariance (raw scale)"}],
             "help": "Correlation basis standardizes every feature to z-scores first, so each contributes equally regardless of units; this is almost always what you want when mixing price levels with oscillators. Covariance basis keeps raw scales and lets high-variance features dominate; only meaningful when all features share comparable units."},
            {"id": "color_by", "label": "Color Points By", "type": "select", "default": "forward_return",
             "options": [{"value": "forward_return", "label": "Forward Return"},
                         {"value": "time", "label": "Time"},
                         {"value": "volume", "label": "Volume"}],
             "help": "What each point's color encodes in the 3D view. Forward return colors each bar by what price did NEXT, so clusters of one color mark regions of factor space that preceded rises or falls. Time reveals how the market drifted through factor space. Volume highlights where activity concentrated."},
            {"id": "forward_horizon", "label": "Forward Horizon (bars)", "type": "number", "default": 10, "min": 1, "max": 100,
             "help": "How many bars ahead the forward return looks when coloring points. Short horizons (1-10) capture immediate follow-through. Longer horizons (20-100) show which factor-space regions preceded larger moves. Only used when coloring by forward return."},
            {"id": "max_points", "label": "Max 3D Points", "type": "number", "default": 2000, "min": 200, "max": 5000, "step": 100,
             "help": "Cap on how many bars are drawn in the 3D scatter. Larger datasets are evenly subsampled down to this count, preserving chronology. 2,000 keeps rotation smooth on most machines; raise it for denser clouds."},
        ],
    },
    {
        "key": "cnn_pattern",
        "name": "CNN Pattern Recognition",
        "category": "deep_learning",
        "description": "1D convolutional neural network for chart pattern detection. Learnable filters detect local candle formations and broader structural patterns directly from price sequences.",
        "script": "deep_learning/cnn_pattern_recognition.py",
        "features_arg": True,
        "deps": ["torch"],
        "dep_imports": ["torch"],
        "gpu": True,
        "params": [
            {"id": "window_size", "label": "Window Size (candles)", "type": "number", "default": 64, "min": 20, "max": 120,
             "help": "Number of candles in each input window. This determines the maximum pattern length the CNN can detect. 64 candles captures most common chart patterns; increase for longer formations."},
            # UI id conv_filters_1; the script has a single --num_filters argument.
            {"id": "num_filters", "label": "Conv Filters", "type": "number", "default": 32, "min": 8, "max": 128, "step": 8,
             "help": "Number of filters in the convolutional layer. Each filter learns to detect a distinct local pattern. 32 filters is a good starting point; increase for more complex pattern vocabularies."},
            {"id": "epochs", "label": "Epochs", "type": "number", "default": 50, "min": 10, "max": 100, "step": 10,
             "help": "Maximum training iterations. Monitor validation accuracy and use early stopping to prevent overfitting."},
            # Script-only parameter, not exposed for the CNN in the ML Studio UI.
            {"id": "target_horizon", "label": "Prediction Horizon", "type": "number", "default": 5, "min": 1, "max": 60,
             "help": "Number of future candles used to create the classification label the detected patterns are trained against."},
        ],
    },
    {
        "key": "autoencoder",
        "name": "Autoencoder Anomaly Detection",
        "category": "deep_learning",
        "description": "Unsupervised network that learns to compress and reconstruct normal market data. High reconstruction error flags abnormal periods such as flash crashes or regime shifts.",
        "script": "deep_learning/autoencoder_anomaly.py",
        "features_arg": True,
        "deps": ["torch"],
        "dep_imports": ["torch"],
        "gpu": True,
        "params": [
            # UI id sequence_length; the script argparse accepts --window_size.
            {"id": "window_size", "label": "Sequence Length", "type": "number", "default": 30, "min": 10, "max": 100,
             "help": "Number of consecutive candles in each input window. Longer sequences capture broader context but require more compression. 30 is suitable for most applications."},
            {"id": "encoding_dim", "label": "Encoding Dimension", "type": "number", "default": 8, "min": 2, "max": 32,
             "help": "Size of the compressed (bottleneck) representation. Smaller values force more aggressive compression, making the model more sensitive to deviations. 8 is a good starting point; reduce for higher sensitivity."},
            {"id": "epochs", "label": "Epochs", "type": "number", "default": 100, "min": 20, "max": 200, "step": 10,
             "help": "Training iterations. Autoencoders should be trained until reconstruction loss stabilises but not so long that they begin to reconstruct anomalous patterns well."},
            # UI id anomaly_threshold; the script argparse accepts --threshold_percentile.
            {"id": "threshold_percentile", "label": "Anomaly Percentile", "type": "number", "default": 95, "min": 90, "max": 99.9, "step": 0.5,
             "help": "Percentile of reconstruction error above which a data point is classified as anomalous. 95 means the top 5% of errors are flagged. Increase to 99 for fewer, more extreme alerts."},
        ],
    },
    {
        "key": "gan_price",
        "name": "GAN Price Simulation",
        "category": "deep_learning",
        "description": "Generative adversarial network for synthetic price path generation. A generator and discriminator compete until the generator produces realistic sequences for stress testing and augmentation.",
        "script": "deep_learning/gan_price_simulation.py",
        "features_arg": True,
        "deps": ["torch"],
        "dep_imports": ["torch"],
        "gpu": True,
        "params": [
            {"id": "sequence_length", "label": "Sequence Length", "type": "number", "default": 48, "min": 12, "max": 100,
             "help": "Length of each generated price sequence in candles. Longer sequences allow the GAN to capture longer-term dependencies but are more difficult to train."},
            {"id": "latent_dim", "label": "Latent Dimension", "type": "number", "default": 100, "min": 10, "max": 200,
             "help": "Dimensionality of the random noise vector fed to the generator. Higher values (100-200) give the generator more expressive power. Lower values constrain the variety of generated sequences."},
            {"id": "epochs", "label": "Training Epochs", "type": "number", "default": 1000, "min": 100, "max": 2000, "step": 100,
             "help": "Total training iterations. GANs require significantly more training than supervised models. Monitor for mode collapse (generator producing repetitive outputs)."},
            # UI id num_samples; the script argparse accepts --num_simulations.
            {"id": "num_simulations", "label": "Samples to Generate", "type": "number", "default": 100, "min": 10, "max": 500, "step": 10,
             "help": "Number of synthetic price paths to generate after training. Use these for Monte Carlo style analysis, strategy stress testing, or dataset augmentation."},
        ],
    },
    {
        "key": "wavelet",
        "name": "Wavelet Decomposition",
        "category": "time_series",
        "description": "Multi-scale time-frequency decomposition that separates long-term trend from cycles and noise. Useful for denoising and multi-scale trend detection on non-stationary data.",
        "script": "time_series/wavelet_decomposition.py",
        "features_arg": True,
        # The script uses a manual Haar-style transform; PyWavelets is NOT required.
        "deps": [],
        "dep_imports": [],
        "gpu": False,
        "params": [
            {"id": "wavelet", "label": "Wavelet Family", "type": "select", "default": "db4",
             "options": [{"value": "db4", "label": "Daubechies 4"}, {"value": "db8", "label": "Daubechies 8"},
                         {"value": "sym5", "label": "Symlet 5"}, {"value": "coif3", "label": "Coiflet 3"},
                         {"value": "haar", "label": "Haar"}],
             "help": "The wavelet family used for decomposition. Daubechies (db4, db8) wavelets balance smoothness and compactness. Symlets offer better symmetry. Haar is simplest but produces blocky decompositions."},
            # UI id decomposition_level; the script argparse accepts --levels.
            {"id": "levels", "label": "Decomposition Levels", "type": "number", "default": 5, "min": 1, "max": 10,
             "help": "Number of decomposition levels. Each level halves the frequency resolution. Higher levels capture longer cycles."},
            # Script-only parameter, not exposed for wavelets in the ML Studio UI.
            {"id": "forecast_steps", "label": "Forecast Steps", "type": "number", "default": 10, "min": 1, "max": 50,
             "help": "Number of steps to project forward from the extracted trend component."},
        ],
    },
    {
        "key": "kalman",
        "name": "Kalman Filter",
        "category": "time_series",
        "description": "Recursive state-space estimator for trend extraction and noise filtering. Combines a predictive model with noisy observations, updating in real time as data arrives.",
        "script": "time_series/kalman_filter.py",
        "features_arg": True,
        "deps": [],
        "dep_imports": [],
        "gpu": False,
        "params": [
            {"id": "model_type", "label": "Model Type", "type": "select", "default": "level_trend",
             "options": [{"value": "level", "label": "Level Only"}, {"value": "level_trend", "label": "Level + Trend"},
                         {"value": "level_trend_season", "label": "Level + Trend + Seasonality"}],
             "help": "Complexity of the state-space model. Level only tracks the price level. Level plus trend adds a velocity component for trending markets. Level plus trend plus seasonality includes periodic patterns."},
            {"id": "process_noise", "label": "Process Noise (Q)", "type": "number", "default": 0.01, "min": 0.0001, "max": 1, "step": 0.001,
             "help": "Process noise covariance (Q). Controls how much the filter expects the true state to change between observations. Higher values make the filter more responsive but noisier. Lower values produce smoother but more lagged estimates."},
            {"id": "measurement_noise", "label": "Measurement Noise (R)", "type": "number", "default": 0.1, "min": 0.001, "max": 10, "step": 0.01,
             "help": "Measurement noise covariance (R). Represents how noisy the observed prices are. Higher values trust the model more than the observations (smoother output). Lower values trust observations more (more responsive)."},
            {"id": "forecast_steps", "label": "Forecast Steps", "type": "number", "default": 10, "min": 1, "max": 50,
             "help": "Number of steps to forecast ahead using the state-space model. The Kalman filter naturally produces forecasts with growing uncertainty intervals."},
            {"id": "smoothing", "label": "Apply Smoothing", "type": "boolean", "default": True,
             "help": "Whether to apply Rauch-Tung-Striebel smoothing after filtering. Smoothing uses future observations to refine past estimates, producing a cleaner signal at the cost of not being causal (cannot be used for live trading)."},
        ],
    },
    {
        "key": "sentiment",
        "name": "Sentiment Analysis (NLP)",
        "category": "sentiment",
        "description": "Financial sentiment analysis from news and market data. Extracts a sentiment signal from text sources and correlates it with subsequent price movement.",
        "script": "sentiment/sentiment_analyzer.py",
        "features_arg": True,
        "deps": [],
        "dep_imports": [],
        "gpu": False,
        "params": [
            {"id": "lookback_period", "label": "Lookback Period", "type": "number", "default": 24, "min": 1, "max": 168,
             "help": "Hours of text data to analyse for current sentiment. Short periods (1-6 hours) capture immediate news impact. Longer periods (24-48 hours) smooth out noise but may miss fast-moving sentiment shifts."},
            {"id": "model", "label": "NLP Model", "type": "select", "default": "finbert",
             "options": [{"value": "finbert", "label": "FinBERT (Finance)"}, {"value": "roberta", "label": "RoBERTa-Sentiment"},
                         {"value": "distilbert", "label": "DistilBERT (Fast)"}, {"value": "vader", "label": "VADER (Rule-based)"}],
             "help": "NLP model for sentiment classification. FinBERT is trained on financial text and understands market-specific language. RoBERTa-Sentiment is more general but accurate. DistilBERT is faster with a minor accuracy tradeoff. VADER is rule-based and fastest."},
            {"id": "source", "label": "Data Sources", "type": "select", "default": "all",
             "options": [{"value": "news", "label": "Financial News Only"}, {"value": "social", "label": "Social Media Only"},
                         {"value": "filings", "label": "SEC Filings"}, {"value": "all", "label": "All Sources Combined"}],
             "help": "Text sources to analyse. Financial news provides institutional views. Social media captures retail sentiment and momentum. SEC filings offer official disclosures. Combined sources give the most complete picture."},
            {"id": "preprocessing", "label": "Text Preprocessing", "type": "select", "default": "standard",
             "options": [{"value": "minimal", "label": "Minimal (Keep All)"}, {"value": "standard", "label": "Standard Cleaning"},
                         {"value": "aggressive", "label": "Aggressive (Remove Noise)"}],
             "help": "Text cleaning before analysis. Minimal keeps emojis and slang (important for social media). Standard removes noise while preserving meaning. Aggressive removes all non-essential text for speed."},
            {"id": "min_confidence", "label": "Min Confidence %", "type": "number", "default": 70, "min": 50, "max": 95, "step": 5,
             "help": "Minimum model confidence to include a text in analysis. Higher thresholds (80-95%) filter to only clear sentiment signals. Lower thresholds (50-70%) include more data but with more noise."},
            {"id": "aggregation", "label": "Score Aggregation", "type": "select", "default": "weighted",
             "options": [{"value": "mean", "label": "Simple Average"}, {"value": "weighted", "label": "Recency Weighted"},
                         {"value": "median", "label": "Median Score"}, {"value": "volume_weighted", "label": "Volume Weighted"}],
             "help": "How to combine multiple sentiment scores. Simple average treats all texts equally. Recency-weighted emphasizes recent texts. Median is robust to outliers. Volume-weighted considers engagement and reach."},
            {"id": "output_type", "label": "Output Type", "type": "select", "default": "composite",
             "options": [{"value": "binary", "label": "Binary (Bull/Bear)"}, {"value": "ternary", "label": "Ternary (+/0/-)"},
                         {"value": "composite", "label": "Composite Score (-1 to 1)"}, {"value": "distribution", "label": "Full Distribution"}],
             "help": "Format of the final sentiment signal. Binary (bull/bear) is simplest. Ternary adds neutral. Composite score (-1 to 1) enables nuanced signals. Distribution shows full probability output."},
            {"id": "include_volume", "label": "Include Volume Metrics", "type": "select", "default": "true",
             "options": [{"value": "true", "label": "Yes"}, {"value": "false", "label": "No"}],
             "help": "Include text volume and engagement metrics alongside sentiment. High volume plus positive sentiment is more bullish than low volume. Useful for detecting when sentiment is driven by a few vocal sources."},
            {"id": "lag_features", "label": "Lagged Features", "type": "number", "default": 3, "min": 0, "max": 12,
             "help": "Include sentiment from previous periods as model features. Captures sentiment momentum and persistence. Helps the model learn how quickly sentiment impacts price."},
        ],
    },
]

MODEL_KEYS = [m["key"] for m in MODELS]

_MODELS_BY_KEY = {m["key"]: m for m in MODELS}


def get_model(key):
    """Return the model dict for a script model key, or None if unknown."""
    return _MODELS_BY_KEY.get(key)
