from __future__ import annotations

# Trading limits
DEFAULT_MAX_POSITION_NOTIONAL = 5_000_000  # 5M
DEFAULT_MAX_ADV_PCT = 0.1  # 10%

# Auth
DEFAULT_ACCESS_TOKEN_TTL_MINUTES = 15
DEFAULT_REFRESH_TOKEN_TTL_DAYS = 1

# API defaults
DEFAULT_CHART_LIMIT = 1000
MAX_CHART_LIMIT = 5000
DEFAULT_PAGINATION_LIMIT = 50
MAX_PAGINATION_LIMIT = 1000

# Network
DEFAULT_TIMEOUT_SECONDS = 30
WEBSOCKET_RECONNECT_DELAY_SECONDS = 5
MAX_WEBSOCKET_RECONNECT_ATTEMPTS = 10

# Redis
DEFAULT_REDIS_POOL_SIZE = 10
REDIS_HEALTH_CHECK_INTERVAL_SECONDS = 30