// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: edgedepth.proto

// Minimal re-declaration of the EdgeDepth terminal wire contract.
//
// This file declares ONLY the messages this gateway emits. The terminal's
// full contract lives in protos/messages.proto in the edgedepth-terminal
// repo and carries dozens of messages a Binance-only gateway can never
// produce. Field numbers here MUST match that file exactly: they are the
// wire format, and a mismatch fails silently rather than loudly.
//
// package pb matches the terminal so the generated types line up 1:1.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Only the stream ids this gateway serves. The terminal's enum runs to 35;
// the gaps here are deliberate, not omissions.
type Stream int32

const (
	Stream_STREAM_UNKNOWN            Stream = 0
	Stream_STREAM_TRADES             Stream = 1
	Stream_STREAM_CANDLES            Stream = 2
	Stream_STREAM_ORDERBOOK          Stream = 3
	Stream_STREAM_STATS              Stream = 4
	Stream_STREAM_LIQUIDATIONS       Stream = 5
	Stream_STREAM_HISTORICAL_CANDLES Stream = 8
	Stream_STREAM_TICK_VOLUME        Stream = 17
	Stream_STREAM_VOLUME_PROFILE     Stream = 26
	Stream_STREAM_TICKER24H          Stream = 29
)

// Enum value maps for Stream.
var (
	Stream_name = map[int32]string{
		0:  "STREAM_UNKNOWN",
		1:  "STREAM_TRADES",
		2:  "STREAM_CANDLES",
		3:  "STREAM_ORDERBOOK",
		4:  "STREAM_STATS",
		5:  "STREAM_LIQUIDATIONS",
		8:  "STREAM_HISTORICAL_CANDLES",
		17: "STREAM_TICK_VOLUME",
		26: "STREAM_VOLUME_PROFILE",
		29: "STREAM_TICKER24H",
	}
	Stream_value = map[string]int32{
		"STREAM_UNKNOWN":            0,
		"STREAM_TRADES":             1,
		"STREAM_CANDLES":            2,
		"STREAM_ORDERBOOK":          3,
		"STREAM_STATS":              4,
		"STREAM_LIQUIDATIONS":       5,
		"STREAM_HISTORICAL_CANDLES": 8,
		"STREAM_TICK_VOLUME":        17,
		"STREAM_VOLUME_PROFILE":     26,
		"STREAM_TICKER24H":          29,
	}
)

func (x Stream) Enum() *Stream {
	p := new(Stream)
	*p = x
	return p
}

func (x Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_edgedepth_proto_enumTypes[0].Descriptor()
}

func (Stream) Type() protoreflect.EnumType {
	return &file_edgedepth_proto_enumTypes[0]
}

func (x Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stream.Descriptor instead.
func (Stream) EnumDescriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{0}
}

type Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pair) Reset() {
	*x = Pair{}
	mi := &file_edgedepth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{0}
}

func (x *Pair) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Pair) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type BookLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Size          float64                `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookLevel) Reset() {
	*x = BookLevel{}
	mi := &file_edgedepth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookLevel) ProtoMessage() {}

func (x *BookLevel) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookLevel.ProtoReflect.Descriptor instead.
func (*BookLevel) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{1}
}

func (x *BookLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookLevel) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type WSPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Stream        Stream                 `protobuf:"varint,2,opt,name=stream,proto3,enum=pb.Stream" json:"stream,omitempty"`
	Timeframe     int64                  `protobuf:"varint,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	EventTimeMs   int64                  `protobuf:"varint,5,opt,name=event_time_ms,json=eventTimeMs,proto3" json:"event_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSPayload) Reset() {
	*x = WSPayload{}
	mi := &file_edgedepth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSPayload) ProtoMessage() {}

func (x *WSPayload) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSPayload.ProtoReflect.Descriptor instead.
func (*WSPayload) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{2}
}

func (x *WSPayload) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *WSPayload) GetStream() Stream {
	if x != nil {
		return x.Stream
	}
	return Stream_STREAM_UNKNOWN
}

func (x *WSPayload) GetTimeframe() int64 {
	if x != nil {
		return x.Timeframe
	}
	return 0
}

func (x *WSPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WSPayload) GetEventTimeMs() int64 {
	if x != nil {
		return x.EventTimeMs
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty           float64                `protobuf:"fixed64,2,opt,name=qty,proto3" json:"qty,omitempty"`
	IsBuy         bool                   `protobuf:"varint,3,opt,name=is_buy,json=isBuy,proto3" json:"is_buy,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_edgedepth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Trade) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

func (x *Trade) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          float64                `protobuf:"fixed64,1,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,3,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,4,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Vbuy          float64                `protobuf:"fixed64,6,opt,name=vbuy,proto3" json:"vbuy,omitempty"`
	Vsell         float64                `protobuf:"fixed64,7,opt,name=vsell,proto3" json:"vsell,omitempty"`
	Tbuy          int64                  `protobuf:"varint,8,opt,name=tbuy,proto3" json:"tbuy,omitempty"`
	Tsell         int64                  `protobuf:"varint,9,opt,name=tsell,proto3" json:"tsell,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,10,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Timeframe     int64                  `protobuf:"varint,11,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Final         bool                   `protobuf:"varint,12,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_edgedepth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{4}
}

func (x *Candle) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Candle) GetVbuy() float64 {
	if x != nil {
		return x.Vbuy
	}
	return 0
}

func (x *Candle) GetVsell() float64 {
	if x != nil {
		return x.Vsell
	}
	return 0
}

func (x *Candle) GetTbuy() int64 {
	if x != nil {
		return x.Tbuy
	}
	return 0
}

func (x *Candle) GetTsell() int64 {
	if x != nil {
		return x.Tsell
	}
	return 0
}

func (x *Candle) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Candle) GetTimeframe() int64 {
	if x != nil {
		return x.Timeframe
	}
	return 0
}

func (x *Candle) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type Candles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeframe     int64                  `protobuf:"varint,1,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Values        []*Candle              `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candles) Reset() {
	*x = Candles{}
	mi := &file_edgedepth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candles) ProtoMessage() {}

func (x *Candles) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candles.ProtoReflect.Descriptor instead.
func (*Candles) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{5}
}

func (x *Candles) GetTimeframe() int64 {
	if x != nil {
		return x.Timeframe
	}
	return 0
}

func (x *Candles) GetValues() []*Candle {
	if x != nil {
		return x.Values
	}
	return nil
}

type Stat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarkPrice       float64                `protobuf:"fixed64,1,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	Funding         float64                `protobuf:"fixed64,2,opt,name=funding,proto3" json:"funding,omitempty"`
	TimestampMs     int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Final           bool                   `protobuf:"varint,4,opt,name=final,proto3" json:"final,omitempty"`
	Timeframe       int64                  `protobuf:"varint,5,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	LiqLongVolume   float64                `protobuf:"fixed64,6,opt,name=liq_long_volume,json=liqLongVolume,proto3" json:"liq_long_volume,omitempty"`
	LiqShortVolume  float64                `protobuf:"fixed64,7,opt,name=liq_short_volume,json=liqShortVolume,proto3" json:"liq_short_volume,omitempty"`
	LiqLongUsd      float64                `protobuf:"fixed64,8,opt,name=liq_long_usd,json=liqLongUsd,proto3" json:"liq_long_usd,omitempty"`
	LiqShortUsd     float64                `protobuf:"fixed64,9,opt,name=liq_short_usd,json=liqShortUsd,proto3" json:"liq_short_usd,omitempty"`
	LiqTotalUsd     float64                `protobuf:"fixed64,10,opt,name=liq_total_usd,json=liqTotalUsd,proto3" json:"liq_total_usd,omitempty"`
	LiqRatio        float64                `protobuf:"fixed64,11,opt,name=liq_ratio,json=liqRatio,proto3" json:"liq_ratio,omitempty"`
	TradeBuy        int64                  `protobuf:"varint,12,opt,name=trade_buy,json=tradeBuy,proto3" json:"trade_buy,omitempty"`
	TradeSell       int64                  `protobuf:"varint,13,opt,name=trade_sell,json=tradeSell,proto3" json:"trade_sell,omitempty"`
	OpenInterestUsd float64                `protobuf:"fixed64,14,opt,name=open_interest_usd,json=openInterestUsd,proto3" json:"open_interest_usd,omitempty"`
	NextFundingTime int64                  `protobuf:"varint,15,opt,name=next_funding_time,json=nextFundingTime,proto3" json:"next_funding_time,omitempty"`
	OiOpen          float64                `protobuf:"fixed64,16,opt,name=oi_open,json=oiOpen,proto3" json:"oi_open,omitempty"`
	OiHigh          float64                `protobuf:"fixed64,17,opt,name=oi_high,json=oiHigh,proto3" json:"oi_high,omitempty"`
	OiLow           float64                `protobuf:"fixed64,18,opt,name=oi_low,json=oiLow,proto3" json:"oi_low,omitempty"`
	OiClose         float64                `protobuf:"fixed64,19,opt,name=oi_close,json=oiClose,proto3" json:"oi_close,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_edgedepth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{6}
}

func (x *Stat) GetMarkPrice() float64 {
	if x != nil {
		return x.MarkPrice
	}
	return 0
}

func (x *Stat) GetFunding() float64 {
	if x != nil {
		return x.Funding
	}
	return 0
}

func (x *Stat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Stat) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *Stat) GetTimeframe() int64 {
	if x != nil {
		return x.Timeframe
	}
	return 0
}

func (x *Stat) GetLiqLongVolume() float64 {
	if x != nil {
		return x.LiqLongVolume
	}
	return 0
}

func (x *Stat) GetLiqShortVolume() float64 {
	if x != nil {
		return x.LiqShortVolume
	}
	return 0
}

func (x *Stat) GetLiqLongUsd() float64 {
	if x != nil {
		return x.LiqLongUsd
	}
	return 0
}

func (x *Stat) GetLiqShortUsd() float64 {
	if x != nil {
		return x.LiqShortUsd
	}
	return 0
}

func (x *Stat) GetLiqTotalUsd() float64 {
	if x != nil {
		return x.LiqTotalUsd
	}
	return 0
}

func (x *Stat) GetLiqRatio() float64 {
	if x != nil {
		return x.LiqRatio
	}
	return 0
}

func (x *Stat) GetTradeBuy() int64 {
	if x != nil {
		return x.TradeBuy
	}
	return 0
}

func (x *Stat) GetTradeSell() int64 {
	if x != nil {
		return x.TradeSell
	}
	return 0
}

func (x *Stat) GetOpenInterestUsd() float64 {
	if x != nil {
		return x.OpenInterestUsd
	}
	return 0
}

func (x *Stat) GetNextFundingTime() int64 {
	if x != nil {
		return x.NextFundingTime
	}
	return 0
}

func (x *Stat) GetOiOpen() float64 {
	if x != nil {
		return x.OiOpen
	}
	return 0
}

func (x *Stat) GetOiHigh() float64 {
	if x != nil {
		return x.OiHigh
	}
	return 0
}

func (x *Stat) GetOiLow() float64 {
	if x != nil {
		return x.OiLow
	}
	return 0
}

func (x *Stat) GetOiClose() float64 {
	if x != nil {
		return x.OiClose
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeframe     int64                  `protobuf:"varint,1,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	Values        []*Stat                `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_edgedepth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{7}
}

func (x *Stats) GetTimeframe() int64 {
	if x != nil {
		return x.Timeframe
	}
	return 0
}

func (x *Stats) GetValues() []*Stat {
	if x != nil {
		return x.Values
	}
	return nil
}

// Field numbers mirror the backend's canonical LiquidationUpdate. The
// terminal proto carries an explicit do-not-renumber warning here: an
// earlier client numbering (price=1) collided varint against fixed64 and
// failed silently on every frame. Do not "tidy" these.
type Liquidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	AvgPrice      float64                `protobuf:"fixed64,3,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Qty           float64                `protobuf:"fixed64,4,opt,name=qty,proto3" json:"qty,omitempty"`
	IsBuy         bool                   `protobuf:"varint,5,opt,name=is_buy,json=isBuy,proto3" json:"is_buy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Liquidation) Reset() {
	*x = Liquidation{}
	mi := &file_edgedepth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Liquidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Liquidation) ProtoMessage() {}

func (x *Liquidation) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Liquidation.ProtoReflect.Descriptor instead.
func (*Liquidation) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{8}
}

func (x *Liquidation) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Liquidation) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Liquidation) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *Liquidation) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Liquidation) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

type BookUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs      int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Asks             []*BookLevel           `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids             []*BookLevel           `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Snapshot         bool                   `protobuf:"varint,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	LastPrice        float64                `protobuf:"fixed64,5,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	FirstUpdateId    int64                  `protobuf:"varint,6,opt,name=first_update_id,json=firstUpdateId,proto3" json:"first_update_id,omitempty"`
	LastUpdateId     int64                  `protobuf:"varint,7,opt,name=last_update_id,json=lastUpdateId,proto3" json:"last_update_id,omitempty"`
	PreviousUpdateId int64                  `protobuf:"varint,8,opt,name=previous_update_id,json=previousUpdateId,proto3" json:"previous_update_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BookUpdate) Reset() {
	*x = BookUpdate{}
	mi := &file_edgedepth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUpdate) ProtoMessage() {}

func (x *BookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUpdate.ProtoReflect.Descriptor instead.
func (*BookUpdate) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{9}
}

func (x *BookUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *BookUpdate) GetAsks() []*BookLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *BookUpdate) GetBids() []*BookLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *BookUpdate) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *BookUpdate) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *BookUpdate) GetFirstUpdateId() int64 {
	if x != nil {
		return x.FirstUpdateId
	}
	return 0
}

func (x *BookUpdate) GetLastUpdateId() int64 {
	if x != nil {
		return x.LastUpdateId
	}
	return 0
}

func (x *BookUpdate) GetPreviousUpdateId() int64 {
	if x != nil {
		return x.PreviousUpdateId
	}
	return 0
}

type TickVolumeLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	BuyVolume     float64                `protobuf:"fixed64,2,opt,name=buy_volume,json=buyVolume,proto3" json:"buy_volume,omitempty"`
	SellVolume    float64                `protobuf:"fixed64,3,opt,name=sell_volume,json=sellVolume,proto3" json:"sell_volume,omitempty"`
	TotalVolume   float64                `protobuf:"fixed64,4,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	TradeCount    int64                  `protobuf:"varint,5,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickVolumeLevel) Reset() {
	*x = TickVolumeLevel{}
	mi := &file_edgedepth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickVolumeLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickVolumeLevel) ProtoMessage() {}

func (x *TickVolumeLevel) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickVolumeLevel.ProtoReflect.Descriptor instead.
func (*TickVolumeLevel) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{10}
}

func (x *TickVolumeLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TickVolumeLevel) GetBuyVolume() float64 {
	if x != nil {
		return x.BuyVolume
	}
	return 0
}

func (x *TickVolumeLevel) GetSellVolume() float64 {
	if x != nil {
		return x.SellVolume
	}
	return 0
}

func (x *TickVolumeLevel) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *TickVolumeLevel) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

type TickVolumeLevels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Levels        []*TickVolumeLevel     `protobuf:"bytes,1,rep,name=levels,proto3" json:"levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickVolumeLevels) Reset() {
	*x = TickVolumeLevels{}
	mi := &file_edgedepth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickVolumeLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickVolumeLevels) ProtoMessage() {}

func (x *TickVolumeLevels) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickVolumeLevels.ProtoReflect.Descriptor instead.
func (*TickVolumeLevels) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{11}
}

func (x *TickVolumeLevels) GetLevels() []*TickVolumeLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

type TickVolumeUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Timeframe     int64                  `protobuf:"varint,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LevelsData    []byte                 `protobuf:"bytes,6,opt,name=levels_data,json=levelsData,proto3" json:"levels_data,omitempty"` // ZSTD-compressed TickVolumeLevels
	TotalVolume   float64                `protobuf:"fixed64,7,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	BuyVolume     float64                `protobuf:"fixed64,8,opt,name=buy_volume,json=buyVolume,proto3" json:"buy_volume,omitempty"`
	SellVolume    float64                `protobuf:"fixed64,9,opt,name=sell_volume,json=sellVolume,proto3" json:"sell_volume,omitempty"`
	TradeCount    int64                  `protobuf:"varint,10,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	HighPrice     float64                `protobuf:"fixed64,11,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	LowPrice      float64                `protobuf:"fixed64,12,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	Poc           float64                `protobuf:"fixed64,13,opt,name=poc,proto3" json:"poc,omitempty"`
	Vah           float64                `protobuf:"fixed64,14,opt,name=vah,proto3" json:"vah,omitempty"`
	Val           float64                `protobuf:"fixed64,15,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickVolumeUpdate) Reset() {
	*x = TickVolumeUpdate{}
	mi := &file_edgedepth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickVolumeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickVolumeUpdate) ProtoMessage() {}

func (x *TickVolumeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickVolumeUpdate.ProtoReflect.Descriptor instead.
func (*TickVolumeUpdate) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{12}
}

func (x *TickVolumeUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TickVolumeUpdate) GetTimeframe() int64 {
	if x != nil {
		return x.Timeframe
	}
	return 0
}

func (x *TickVolumeUpdate) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TickVolumeUpdate) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TickVolumeUpdate) GetLevelsData() []byte {
	if x != nil {
		return x.LevelsData
	}
	return nil
}

func (x *TickVolumeUpdate) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *TickVolumeUpdate) GetBuyVolume() float64 {
	if x != nil {
		return x.BuyVolume
	}
	return 0
}

func (x *TickVolumeUpdate) GetSellVolume() float64 {
	if x != nil {
		return x.SellVolume
	}
	return 0
}

func (x *TickVolumeUpdate) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *TickVolumeUpdate) GetHighPrice() float64 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

func (x *TickVolumeUpdate) GetLowPrice() float64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *TickVolumeUpdate) GetPoc() float64 {
	if x != nil {
		return x.Poc
	}
	return 0
}

func (x *TickVolumeUpdate) GetVah() float64 {
	if x != nil {
		return x.Vah
	}
	return 0
}

func (x *TickVolumeUpdate) GetVal() float64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Ticker24HEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // uppercase, matches Binance
	LastPrice     float64                `protobuf:"fixed64,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	ChangePct     float64                `protobuf:"fixed64,3,opt,name=change_pct,json=changePct,proto3" json:"change_pct,omitempty"`
	VolumeQuote   float64                `protobuf:"fixed64,4,opt,name=volume_quote,json=volumeQuote,proto3" json:"volume_quote,omitempty"`
	EventTimeMs   int64                  `protobuf:"varint,5,opt,name=event_time_ms,json=eventTimeMs,proto3" json:"event_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticker24HEntry) Reset() {
	*x = Ticker24HEntry{}
	mi := &file_edgedepth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker24HEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker24HEntry) ProtoMessage() {}

func (x *Ticker24HEntry) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker24HEntry.ProtoReflect.Descriptor instead.
func (*Ticker24HEntry) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{13}
}

func (x *Ticker24HEntry) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Ticker24HEntry) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *Ticker24HEntry) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

func (x *Ticker24HEntry) GetVolumeQuote() float64 {
	if x != nil {
		return x.VolumeQuote
	}
	return 0
}

func (x *Ticker24HEntry) GetEventTimeMs() int64 {
	if x != nil {
		return x.EventTimeMs
	}
	return 0
}

type Ticker24HUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Ticker24HEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticker24HUpdate) Reset() {
	*x = Ticker24HUpdate{}
	mi := &file_edgedepth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker24HUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker24HUpdate) ProtoMessage() {}

func (x *Ticker24HUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker24HUpdate.ProtoReflect.Descriptor instead.
func (*Ticker24HUpdate) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{14}
}

func (x *Ticker24HUpdate) GetEntries() []*Ticker24HEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Ticker24HUpdate) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type VolumeProfileLevel struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Price            float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	BuyVolume        float64                `protobuf:"fixed64,2,opt,name=buy_volume,json=buyVolume,proto3" json:"buy_volume,omitempty"`
	SellVolume       float64                `protobuf:"fixed64,3,opt,name=sell_volume,json=sellVolume,proto3" json:"sell_volume,omitempty"`
	TotalVolume      float64                `protobuf:"fixed64,4,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	TradeCount       int64                  `protobuf:"varint,5,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	VolumePercentage float64                `protobuf:"fixed64,6,opt,name=volume_percentage,json=volumePercentage,proto3" json:"volume_percentage,omitempty"`
	IsPoc            bool                   `protobuf:"varint,7,opt,name=is_poc,json=isPoc,proto3" json:"is_poc,omitempty"`
	InValueArea      bool                   `protobuf:"varint,8,opt,name=in_value_area,json=inValueArea,proto3" json:"in_value_area,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VolumeProfileLevel) Reset() {
	*x = VolumeProfileLevel{}
	mi := &file_edgedepth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeProfileLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeProfileLevel) ProtoMessage() {}

func (x *VolumeProfileLevel) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeProfileLevel.ProtoReflect.Descriptor instead.
func (*VolumeProfileLevel) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{15}
}

func (x *VolumeProfileLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *VolumeProfileLevel) GetBuyVolume() float64 {
	if x != nil {
		return x.BuyVolume
	}
	return 0
}

func (x *VolumeProfileLevel) GetSellVolume() float64 {
	if x != nil {
		return x.SellVolume
	}
	return 0
}

func (x *VolumeProfileLevel) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *VolumeProfileLevel) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *VolumeProfileLevel) GetVolumePercentage() float64 {
	if x != nil {
		return x.VolumePercentage
	}
	return 0
}

func (x *VolumeProfileLevel) GetIsPoc() bool {
	if x != nil {
		return x.IsPoc
	}
	return false
}

func (x *VolumeProfileLevel) GetInValueArea() bool {
	if x != nil {
		return x.InValueArea
	}
	return false
}

type VolumeProfileResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartTime       int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Levels          []*VolumeProfileLevel  `protobuf:"bytes,3,rep,name=levels,proto3" json:"levels,omitempty"`
	Poc             float64                `protobuf:"fixed64,4,opt,name=poc,proto3" json:"poc,omitempty"`
	Vah             float64                `protobuf:"fixed64,5,opt,name=vah,proto3" json:"vah,omitempty"`
	Val             float64                `protobuf:"fixed64,6,opt,name=val,proto3" json:"val,omitempty"`
	TotalVolume     float64                `protobuf:"fixed64,7,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	ValueAreaVolume float64                `protobuf:"fixed64,8,opt,name=value_area_volume,json=valueAreaVolume,proto3" json:"value_area_volume,omitempty"`
	PocIndex        int32                  `protobuf:"varint,9,opt,name=poc_index,json=pocIndex,proto3" json:"poc_index,omitempty"`
	VahIndex        int32                  `protobuf:"varint,10,opt,name=vah_index,json=vahIndex,proto3" json:"vah_index,omitempty"`
	ValIndex        int32                  `protobuf:"varint,11,opt,name=val_index,json=valIndex,proto3" json:"val_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VolumeProfileResponse) Reset() {
	*x = VolumeProfileResponse{}
	mi := &file_edgedepth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeProfileResponse) ProtoMessage() {}

func (x *VolumeProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edgedepth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeProfileResponse.ProtoReflect.Descriptor instead.
func (*VolumeProfileResponse) Descriptor() ([]byte, []int) {
	return file_edgedepth_proto_rawDescGZIP(), []int{16}
}

func (x *VolumeProfileResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *VolumeProfileResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *VolumeProfileResponse) GetLevels() []*VolumeProfileLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

func (x *VolumeProfileResponse) GetPoc() float64 {
	if x != nil {
		return x.Poc
	}
	return 0
}

func (x *VolumeProfileResponse) GetVah() float64 {
	if x != nil {
		return x.Vah
	}
	return 0
}

func (x *VolumeProfileResponse) GetVal() float64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *VolumeProfileResponse) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *VolumeProfileResponse) GetValueAreaVolume() float64 {
	if x != nil {
		return x.ValueAreaVolume
	}
	return 0
}

func (x *VolumeProfileResponse) GetPocIndex() int32 {
	if x != nil {
		return x.PocIndex
	}
	return 0
}

func (x *VolumeProfileResponse) GetVahIndex() int32 {
	if x != nil {
		return x.VahIndex
	}
	return 0
}

func (x *VolumeProfileResponse) GetValIndex() int32 {
	if x != nil {
		return x.ValIndex
	}
	return 0
}

var File_edgedepth_proto protoreflect.FileDescriptor

const file_edgedepth_proto_rawDesc = "" +
	"\n" +
	"\x0fedgedepth.proto\x12\x02pb\":\n" +
	"\x04Pair\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"5\n" +
	"\tBookLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x01R\x04size\"\xa3\x01\n" +
	"\tWSPayload\x12\x1c\n" +
	"\x04pair\x18\x01 \x01(\v2\b.pb.PairR\x04pair\x12\"\n" +
	"\x06stream\x18\x02 \x01(\x0e2\n" +
	".pb.StreamR\x06stream\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\x03R\ttimeframe\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\"\n" +
	"\revent_time_ms\x18\x05 \x01(\x03R\veventTimeMs\"i\n" +
	"\x05Trade\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x01R\x03qty\x12\x15\n" +
	"\x06is_buy\x18\x03 \x01(\bR\x05isBuy\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\"\x9b\x02\n" +
	"\x06Candle\x12\x12\n" +
	"\x04open\x18\x01 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x03 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x04 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12\x12\n" +
	"\x04vbuy\x18\x06 \x01(\x01R\x04vbuy\x12\x14\n" +
	"\x05vsell\x18\a \x01(\x01R\x05vsell\x12\x12\n" +
	"\x04tbuy\x18\b \x01(\x03R\x04tbuy\x12\x14\n" +
	"\x05tsell\x18\t \x01(\x03R\x05tsell\x12!\n" +
	"\ftimestamp_ms\x18\n" +
	" \x01(\x03R\vtimestampMs\x12\x1c\n" +
	"\ttimeframe\x18\v \x01(\x03R\ttimeframe\x12\x14\n" +
	"\x05final\x18\f \x01(\bR\x05final\"K\n" +
	"\aCandles\x12\x1c\n" +
	"\ttimeframe\x18\x01 \x01(\x03R\ttimeframe\x12\"\n" +
	"\x06values\x18\x02 \x03(\v2\n" +
	".pb.CandleR\x06values\"\xe7\x04\n" +
	"\x04Stat\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x01 \x01(\x01R\tmarkPrice\x12\x18\n" +
	"\afunding\x18\x02 \x01(\x01R\afunding\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05final\x18\x04 \x01(\bR\x05final\x12\x1c\n" +
	"\ttimeframe\x18\x05 \x01(\x03R\ttimeframe\x12&\n" +
	"\x0fliq_long_volume\x18\x06 \x01(\x01R\rliqLongVolume\x12(\n" +
	"\x10liq_short_volume\x18\a \x01(\x01R\x0eliqShortVolume\x12 \n" +
	"\fliq_long_usd\x18\b \x01(\x01R\n" +
	"liqLongUsd\x12\"\n" +
	"\rliq_short_usd\x18\t \x01(\x01R\vliqShortUsd\x12\"\n" +
	"\rliq_total_usd\x18\n" +
	" \x01(\x01R\vliqTotalUsd\x12\x1b\n" +
	"\tliq_ratio\x18\v \x01(\x01R\bliqRatio\x12\x1b\n" +
	"\ttrade_buy\x18\f \x01(\x03R\btradeBuy\x12\x1d\n" +
	"\n" +
	"trade_sell\x18\r \x01(\x03R\ttradeSell\x12*\n" +
	"\x11open_interest_usd\x18\x0e \x01(\x01R\x0fopenInterestUsd\x12*\n" +
	"\x11next_funding_time\x18\x0f \x01(\x03R\x0fnextFundingTime\x12\x17\n" +
	"\aoi_open\x18\x10 \x01(\x01R\x06oiOpen\x12\x17\n" +
	"\aoi_high\x18\x11 \x01(\x01R\x06oiHigh\x12\x15\n" +
	"\x06oi_low\x18\x12 \x01(\x01R\x05oiLow\x12\x19\n" +
	"\boi_close\x18\x13 \x01(\x01R\aoiClose\"G\n" +
	"\x05Stats\x12\x1c\n" +
	"\ttimeframe\x18\x01 \x01(\x03R\ttimeframe\x12 \n" +
	"\x06values\x18\x02 \x03(\v2\b.pb.StatR\x06values\"\x8c\x01\n" +
	"\vLiquidation\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1b\n" +
	"\tavg_price\x18\x03 \x01(\x01R\bavgPrice\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x01R\x03qty\x12\x15\n" +
	"\x06is_buy\x18\x05 \x01(\bR\x05isBuy\"\xac\x02\n" +
	"\n" +
	"BookUpdate\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\x12!\n" +
	"\x04asks\x18\x02 \x03(\v2\r.pb.BookLevelR\x04asks\x12!\n" +
	"\x04bids\x18\x03 \x03(\v2\r.pb.BookLevelR\x04bids\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\bR\bsnapshot\x12\x1d\n" +
	"\n" +
	"last_price\x18\x05 \x01(\x01R\tlastPrice\x12&\n" +
	"\x0ffirst_update_id\x18\x06 \x01(\x03R\rfirstUpdateId\x12$\n" +
	"\x0elast_update_id\x18\a \x01(\x03R\flastUpdateId\x12,\n" +
	"\x12previous_update_id\x18\b \x01(\x03R\x10previousUpdateId\"\xab\x01\n" +
	"\x0fTickVolumeLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"buy_volume\x18\x02 \x01(\x01R\tbuyVolume\x12\x1f\n" +
	"\vsell_volume\x18\x03 \x01(\x01R\n" +
	"sellVolume\x12!\n" +
	"\ftotal_volume\x18\x04 \x01(\x01R\vtotalVolume\x12\x1f\n" +
	"\vtrade_count\x18\x05 \x01(\x03R\n" +
	"tradeCount\"?\n" +
	"\x10TickVolumeLevels\x12+\n" +
	"\x06levels\x18\x01 \x03(\v2\x13.pb.TickVolumeLevelR\x06levels\"\xaa\x03\n" +
	"\x10TickVolumeUpdate\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\x03R\ttimeframe\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1f\n" +
	"\vlevels_data\x18\x06 \x01(\fR\n" +
	"levelsData\x12!\n" +
	"\ftotal_volume\x18\a \x01(\x01R\vtotalVolume\x12\x1d\n" +
	"\n" +
	"buy_volume\x18\b \x01(\x01R\tbuyVolume\x12\x1f\n" +
	"\vsell_volume\x18\t \x01(\x01R\n" +
	"sellVolume\x12\x1f\n" +
	"\vtrade_count\x18\n" +
	" \x01(\x03R\n" +
	"tradeCount\x12\x1d\n" +
	"\n" +
	"high_price\x18\v \x01(\x01R\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\f \x01(\x01R\blowPrice\x12\x10\n" +
	"\x03poc\x18\r \x01(\x01R\x03poc\x12\x10\n" +
	"\x03vah\x18\x0e \x01(\x01R\x03vah\x12\x10\n" +
	"\x03val\x18\x0f \x01(\x01R\x03valJ\x04\b\x01\x10\x02\"\xad\x01\n" +
	"\x0eTicker24hEntry\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\x01R\tlastPrice\x12\x1d\n" +
	"\n" +
	"change_pct\x18\x03 \x01(\x01R\tchangePct\x12!\n" +
	"\fvolume_quote\x18\x04 \x01(\x01R\vvolumeQuote\x12\"\n" +
	"\revent_time_ms\x18\x05 \x01(\x03R\veventTimeMs\"b\n" +
	"\x0fTicker24hUpdate\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.pb.Ticker24hEntryR\aentries\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"\x96\x02\n" +
	"\x12VolumeProfileLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"buy_volume\x18\x02 \x01(\x01R\tbuyVolume\x12\x1f\n" +
	"\vsell_volume\x18\x03 \x01(\x01R\n" +
	"sellVolume\x12!\n" +
	"\ftotal_volume\x18\x04 \x01(\x01R\vtotalVolume\x12\x1f\n" +
	"\vtrade_count\x18\x05 \x01(\x03R\n" +
	"tradeCount\x12+\n" +
	"\x11volume_percentage\x18\x06 \x01(\x01R\x10volumePercentage\x12\x15\n" +
	"\x06is_poc\x18\a \x01(\bR\x05isPoc\x12\"\n" +
	"\rin_value_area\x18\b \x01(\bR\vinValueArea\"\xdd\x02\n" +
	"\x15VolumeProfileResponse\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12.\n" +
	"\x06levels\x18\x03 \x03(\v2\x16.pb.VolumeProfileLevelR\x06levels\x12\x10\n" +
	"\x03poc\x18\x04 \x01(\x01R\x03poc\x12\x10\n" +
	"\x03vah\x18\x05 \x01(\x01R\x03vah\x12\x10\n" +
	"\x03val\x18\x06 \x01(\x01R\x03val\x12!\n" +
	"\ftotal_volume\x18\a \x01(\x01R\vtotalVolume\x12*\n" +
	"\x11value_area_volume\x18\b \x01(\x01R\x0fvalueAreaVolume\x12\x1b\n" +
	"\tpoc_index\x18\t \x01(\x05R\bpocIndex\x12\x1b\n" +
	"\tvah_index\x18\n" +
	" \x01(\x05R\bvahIndex\x12\x1b\n" +
	"\tval_index\x18\v \x01(\x05R\bvalIndex*\xec\x01\n" +
	"\x06Stream\x12\x12\n" +
	"\x0eSTREAM_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSTREAM_TRADES\x10\x01\x12\x12\n" +
	"\x0eSTREAM_CANDLES\x10\x02\x12\x14\n" +
	"\x10STREAM_ORDERBOOK\x10\x03\x12\x10\n" +
	"\fSTREAM_STATS\x10\x04\x12\x17\n" +
	"\x13STREAM_LIQUIDATIONS\x10\x05\x12\x1d\n" +
	"\x19STREAM_HISTORICAL_CANDLES\x10\b\x12\x16\n" +
	"\x12STREAM_TICK_VOLUME\x10\x11\x12\x19\n" +
	"\x15STREAM_VOLUME_PROFILE\x10\x1a\x12\x14\n" +
	"\x10STREAM_TICKER24H\x10\x1dB1Z/github.com/edgedepthhq/edgedepth-gateway/pkg/pbb\x06proto3"

var (
	file_edgedepth_proto_rawDescOnce sync.Once
	file_edgedepth_proto_rawDescData []byte
)

func file_edgedepth_proto_rawDescGZIP() []byte {
	file_edgedepth_proto_rawDescOnce.Do(func() {
		file_edgedepth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edgedepth_proto_rawDesc), len(file_edgedepth_proto_rawDesc)))
	})
	return file_edgedepth_proto_rawDescData
}

var file_edgedepth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_edgedepth_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_edgedepth_proto_goTypes = []any{
	(Stream)(0),                   // 0: pb.Stream
	(*Pair)(nil),                  // 1: pb.Pair
	(*BookLevel)(nil),             // 2: pb.BookLevel
	(*WSPayload)(nil),             // 3: pb.WSPayload
	(*Trade)(nil),                 // 4: pb.Trade
	(*Candle)(nil),                // 5: pb.Candle
	(*Candles)(nil),               // 6: pb.Candles
	(*Stat)(nil),                  // 7: pb.Stat
	(*Stats)(nil),                 // 8: pb.Stats
	(*Liquidation)(nil),           // 9: pb.Liquidation
	(*BookUpdate)(nil),            // 10: pb.BookUpdate
	(*TickVolumeLevel)(nil),       // 11: pb.TickVolumeLevel
	(*TickVolumeLevels)(nil),      // 12: pb.TickVolumeLevels
	(*TickVolumeUpdate)(nil),      // 13: pb.TickVolumeUpdate
	(*Ticker24HEntry)(nil),        // 14: pb.Ticker24hEntry
	(*Ticker24HUpdate)(nil),       // 15: pb.Ticker24hUpdate
	(*VolumeProfileLevel)(nil),    // 16: pb.VolumeProfileLevel
	(*VolumeProfileResponse)(nil), // 17: pb.VolumeProfileResponse
}
var file_edgedepth_proto_depIdxs = []int32{
	1,  // 0: pb.WSPayload.pair:type_name -> pb.Pair
	0,  // 1: pb.WSPayload.stream:type_name -> pb.Stream
	5,  // 2: pb.Candles.values:type_name -> pb.Candle
	7,  // 3: pb.Stats.values:type_name -> pb.Stat
	2,  // 4: pb.BookUpdate.asks:type_name -> pb.BookLevel
	2,  // 5: pb.BookUpdate.bids:type_name -> pb.BookLevel
	11, // 6: pb.TickVolumeLevels.levels:type_name -> pb.TickVolumeLevel
	14, // 7: pb.Ticker24hUpdate.entries:type_name -> pb.Ticker24hEntry
	16, // 8: pb.VolumeProfileResponse.levels:type_name -> pb.VolumeProfileLevel
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_edgedepth_proto_init() }
func file_edgedepth_proto_init() {
	if File_edgedepth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edgedepth_proto_rawDesc), len(file_edgedepth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edgedepth_proto_goTypes,
		DependencyIndexes: file_edgedepth_proto_depIdxs,
		EnumInfos:         file_edgedepth_proto_enumTypes,
		MessageInfos:      file_edgedepth_proto_msgTypes,
	}.Build()
	File_edgedepth_proto = out.File
	file_edgedepth_proto_goTypes = nil
	file_edgedepth_proto_depIdxs = nil
}
